apiVersion: v1
kind: Binding
metadata:
  name: nginx

target:
  apiversion: v1
  kind: Node
  name: node02

kubectl proxy --api-prefix=/

curl --header "content-type: application/json" --request POST --data '{apiversion: v1.....}' http://$server/api/v1/namespaces/default/pods/<podname>/binding/