apiVersion: v1
kind: Service
metadata:
  name: test-service
  labels:
    app-service: test-service

spec:
  type: clusterIP
  ports:
    - targetPort: 80
      port: 80

  selector:
    app_type: backend