apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: default
  labels:
    app_type: frontend
spec:
  containers:
    - name: test-pod
      image: nginx
      command:
        - sh
        - -c
        - sleep 2000
  nodeName: node01
