apiVersion: v1
kind: service
metadata:
  name: test-service
  labels:
    app-service: test-service

spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector:
    app_type: frontend